name: CICD

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # - name: Set up Python
    #   uses: actions/setup-python@v2
    #   with:
    #     python-version: 3.8
    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install -r backend/requirements.txt
    #     pip install pylint
    # - name: Lint code
    #   run: |
    #     pylint backend
    #   continue-on-error: true

    # - name: SonarCloud Scan
    #   uses: sonarsource/sonarcloud-github-action@master
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
    #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Build and push Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_IMAGE_FRONTEND: ${{ secrets.DOCKER_IMAGE_FRONTEND }}
        DOCKER_IMAGE_BACKTEND: ${{ secrets.DOCKER_IMAGE_BACKEND }}
      run: |
        cd ./frontend
        docker build -t $DOCKER_USERNAME/$DOCKER_IMAGE_FRONTEND:actionv1 .
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        docker push $DOCKER_USERNAME/$DOCKER_IMAGE_FRONTEND:actionv1
        cd ../backend
        docker build -t $DOCKER_USERNAME/$DOCKER_IMAGE_BACKEND:actionv1 .
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        docker push $DOCKER_USERNAME/$DOCKER_IMAGE_BACKEND:actionv1
